apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: demo-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ooransa/osaora-demo-operator-bundle:v0.0.1
  displayName: Demo Request Operator
  publisher: Osama Oransa
  updateStrategy:
    registryPoll:
      interval: 10m
